name: Locker
on:
  schedule:
    - cron: 0 8 * * * # 1:00am PT
  workflow_dispatch:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout triage-actions
        uses: actions/checkout@v2
        with:
          repository: "microsoft/vscode-azuretools"
          path: ./azuretools
          ref: v0.2.0-triage-actions
      - name: npm install
        run: npm install --production --prefix ./azuretools/triage-actions
      - name: Run Locker
        uses: ./azuretools/triage-actions/locker
        with:
          daysSinceClose: 45
          daysSinceUpdate: 7
